- name: Install cloud-init
  dnf:
    name:
      - cloud-init
      - cloud-utils-growpart
      - dracut-config-generic

- name: Enable cloud-init services
  service:
    name: "{{ item }}"
    enabled: true
  with_items:
    - cloud-config
    - cloud-init
    - cloud-init-local
    - cloud-final

- name: Configure cloud-init user name
  replace:
    dest: /etc/cloud/cloud.cfg
    regexp: '^(\s+name:).*$'
    replace: "\\1 {{ cloud_init_user }}"
  when: cloud_init_user | length > 0


- include_tasks: azure.yml
  when: cloud_platform == 'azure'

- ansible.builtin.include_tasks: oci.yaml
  when: cloud_platform == 'oci'
