---
- name: Remove linux-firmware
  dnf:
    name:
      - linux-firmware
    state: absent

- name: Install additional software
  dnf:
    name:
      - cockpit-system
      - cockpit-ws
      - dnf-utils
      - gdisk
      - nfs-utils
      - rsync
      - tar
      - tuned
      - tcpdump

- name: Find persistent-net.rules
  find:
    paths: /etc/udev/rules.d
    patterns: 70*
  register: net_rules

- name: Delete persistent-net.rules
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ net_rules.files }}"

- name: Configure /etc/sysconfig/network
  lineinfile:
    path: /etc/sysconfig/network
    line: "{{ item }}"
  with_items:
    - NETWORKING=yes
    - NOZEROCONF=yes

- name: Configure /etc/sysconfig/network-scripts/ifcfg-eth0
  copy:
    src: ifcfg-eth0
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    owner: root
    group: root
    mode: 0644

- name: Disable consistent network device naming
  file:
    src: /dev/null
    dest: /etc/udev/rules.d/80-net-name-slot.rules
    owner: root
    group: root
    state: link

- name: Disable virtual terminals allocation by logind
  replace:
    path: '/etc/systemd/logind.conf'
    regexp: '^#?NAutoVTs=\d+'
    replace: 'NAutoVTs=0'

- name: Configure NetworkManager default DHCP timeout
  community.general.ini_file:
    path: /etc/NetworkManager/conf.d/dhcp.conf
    section: connection
    option: ipv4.dhcp-timeout
    value: 300
    owner: root
    group: root
    mode: 0644
    seuser: system_u

- name: Set default kernel package type to kernel
  replace:
    path: /etc/sysconfig/kernel
    regexp: '^(DEFAULTKERNEL=).*$'
    replace: '\1kernel'

- name: Setup iSCSI for root partition
  block:
    - name: Install iSCSI daemon and utility programs
      dnf:
        name:
          - iscsi-initiator-utils
          - iscsi-initiator-utils-iscsiuio
          - device-mapper-multipath
        state: present

    - name: Setup root on ISCSI
      replace:
        path: /etc/iscsi/iscsid.conf
        regexp: "{{ item.find }}"
        replace: "{{ item.replace }}"
      loop:
        - {
            find: "(.*)replacement_timeout(.*)",
            replace: "node.session.timeo.replacement_timeout = 6000",
          }
        - {
            find: "(.*)noop_out_interval(.*)",
            replace: "node.conn[0].timeo.noop_out_interval = 0",
          }
        - {
            find: "(.*)noop_out_timeout(.*)",
            replace: "node.conn[0].timeo.noop_out_timeout = 0",
          }

- name: Set up root on iSCSI for Bare Metal instances
  ansible.builtin.replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=(.*)'
    replace: 'GRUB_CMDLINE_LINUX="console=tty0 console=ttyS0,115200n8 no_timer_check biosdevname=0 net.ifnames=0 netroot=iscsi:169.254.0.2:::1:iqn.2015-02.oracle.boot:uefi rd.iscsi.param=node.session.timeo.replacement_timeout=6000 libiscsi.debug_libiscsi_eh=1 nvme_core.shutdown_timeout=10"'

- name: Generate the GRUB configuration file
  command: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: Add OCI NTP Service to chrony config
  lineinfile:
    path: /etc/chrony.conf
    line: "{{ item }}"
  with_items:
    - '# Oracle Cloud Infrastructure NTP Service'
    - 'server 169.254.169.254 prefer iburst'

# The public download links of Oracle Cloud Agent are not available anymore
# - name: Set up Oracle Cloud Agent
#   block:
#     - name: Import Oracle Linux 8 GPG Public key
#       rpm_key:
#         state: present
#         key: "{{ ol8_gpg_key_url }}"
#       when: ansible_facts['distribution_major_version'] == '8'
#
#     - name: Install Oracle Cloud Agent
#       dnf:
#         name:
#           - "{{ oracle_cloud_agent_url_x86_64 }}"
#           - librepo
#           - python3-librepo
#         state: present
#       when:
#         - ansible_facts['architecture'] == 'x86_64'
#         - ansible_facts['distribution_major_version'] == '8'
#
#     - name: Install Oracle Cloud Agent
#       dnf:
#         name:
#           - "{{ oracle_cloud_agent_url_aarch64 }}"
#           - librepo
#           - python3-librepo
#         state: present
#       when:
#         - ansible_facts['architecture'] == 'aarch64'
#         - ansible_facts['distribution_major_version'] == '8'

- name: Permit only SSH service on firewalld
  firewalld:
    service: "{{ item }}"
    state: disabled
    permanent: yes
  loop:
    - cockpit
    - dhcpv6-client

- name: Set virtual-guest as default profile for tuned
  lineinfile:
    path: /etc/tuned/active_profile
    line: virtual-guest
    create: yes

- name: Add multipath in the initramfs file system
  lineinfile:
    path: /etc/dracut.conf.d/multipath.conf
    line: 'add_dracutmodules+=" multipath "'
    create: true
    owner: root
    group: root
    mode: 0644

- name: Regenerate the initramfs
  command: dracut -f --regenerate-all

- name: Enable the multipath
  command: mpathconf --enable

- name: Disable root login
  user:
    name: root
    password: '!!'
