---
galaxy_info:
  role_name: vmware_guest
  author: Eugene Zamriy
  description: Installs open-vm-tools
  license: MIT
  min_ansible_version: '2.5'
  platforms:
    - name: EL
      versions:
        - '8'
  galaxy_tags:
    - guest
    - system
    - vmware

dependencies: []
